### ISSUE TITLE
track: Some (small) changes before 0.8

### ISSUE THREAD

**Issue by daudix-UFO** [GradienceTeam/Gradience#758]
### To-Do

A few things that would be good to do before 0.8 but are not blockers, tracked in this list to not forget about them

- [ ] Make DnD between color buttons work (you can drag the color from one button to other but it doesn't change the color value right now)
- [ ] Fix rename text box in Preset Manager revealing from right and not left as in main window https://github.com/GradienceTeam/Gradience/issues/758#issuecomment-1510434548
- [ ] #736
- [ ] Replace logout message with toast <sup>[HIG](https://developer.gnome.org/hig/patterns/feedback/toasts.html)</sup>
- [ ] Make something with `translator-credits`, I have made it vary from lang to lang, but now link/mail is broken as Weblate is confused by using XML syntax in Python file
- [x] _Not sure_ Add support for [`Thumbnail Colors`](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/named-colors.html#thumbnail-colors)
- [ ] "Pick Color" button in color entry to quickly open color picking dialog
- [ ] Simplify welcome window by removing useless steps like selecting theming options and installing themes pages

> ![image](https://user-images.githubusercontent.com/77155297/232658999-5aeffaba-c8c1-443d-85cb-91ffa0e64f5a.png)
>
> ![image](https://user-images.githubusercontent.com/77155297/232658911-8eed9191-7f4b-471a-8368-25bb88617136.png)

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

**Comment by tfuxu** [comment]
There's no need to move to the new 4.10 widgets, as the old ones will be removed in GTK 5, which isn't even in the workings yet. Porting now would make Gradience incompatible with most native users, so I would wait with moving to new widgets until at least 4.10 will be available in most distributions. 

Check out October post on GTK blog talking about 4.10 deprecations for more info: https://blog.gtk.org/2022/10/

**Comment by daudix-UFO** [comment]
> Fix rename text box in Preset Manager revealing from right and not left as in main window

This can be fixed by making rename button the first button in a row, this is also a good chance to use the new layout [rename / apply / star]

**Comment by 0xMRTT** [comment]
@daudix-UFO can you explain 

>  Make DnD between color buttons work (you can drag the color from one button to other but it doesn't change the color value right now)

Is it this ? 
![image](https://github.com/GradienceTeam/Gradience/assets/105598867/da039f14-1f41-47c0-8464-e903c1150d01)

**Comment by daudix-UFO** [comment]
No, I mean the color button in gradience itself can be dragged on the other button, and it will copy the color, but hex itself doesn't respect this
