### ISSUE TITLE
⚠️ Shell Engine Roadmap (see for list of bugs)

### ISSUE THREAD

**Issue by tfuxu** [GradienceTeam/Gradience#763]
### Feature description

The list below shows features that needs to be implemented to make Shell Engine fully "feature-complete". Items in "Issues" list should be all checked out before 0.8.0 release.

### Roadmap:
- [ ] Add explanations for custom Shell colors
- [ ] Implement panel theming
- [ ] Theme export option (allow user to choose Shell version for which to generate the theme)
- [ ] Automatic theme variant detection (implement after preset format redesign)
- [ ] Revert to previous theme option (requires backup functionality implemented)
- [ ] System-wide theming (required to theme lock screen and GDM)
- [ ] Theme other colorable Shell assets

### Issues:
- [x] Fix Quick Settings menu not being themed in GNOME 44
- [x] Fix date text color in Today's calendar widget using the same variable as foreground color for accent-colored elements
- [x] Fix icons in Quick Settings items not using foreground color for accent-colored elements
- [x] Adapt on-board keyboard to support custom themes

### Additional Context

There is a Nightly Flatpak Repo available [here](https://github.com/GradienceTeam/Gradience#nightly-remote) for trying and reporting bugs of the upcoming Gradience version

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

**Comment by V-Mann-Nick** [comment]
Thank you very much for the awesome work. I'm already using the shell engine and it looks really great. I really only noticed one minor thing: the dropdown in the quick settings have default color.

![image](https://user-images.githubusercontent.com/47660390/236888576-0fd12a2c-9fac-4fa9-9903-90bbb5a5d5a9.png)

**Comment by tfuxu** [comment]
Thank you for your kind words! The issue you described here is the first item in issues list, I'll try to fix it as soon as I have some free time this week.

**Comment by V-Mann-Nick** [comment]
Perfect. Appreciate it a lot. Sorry for my redundant comment.

**Comment by 0xMRTT** [comment]
Shell doesn't support `@var_name` so a function for converting each `@var_name` to the hex/rgb value is needed since `@` vars are LibAdwaita only

**Comment by tfuxu** [comment]
> Shell doesn't support `@var_name` so a function for converting each `@var_name` to the hex/rgb value is needed since `@` vars are LibAdwaita only

Fixed in 1a5b1f4. We already have a function to handle that, it was just buggy.

**Comment by sidevesh** [comment]
@tfuxu Can we add touch keyboard keys to this ? The keyboard background allready uses the theme colors, only the keys need to be adapted.
![image](https://github.com/GradienceTeam/Gradience/assets/17254413/be38b51a-d184-4618-99ab-94248fe36768)

**Comment by 0xMRTT** [comment]
@sidevesh yes it should be possible if we get the css name of this elements (I'm searching rn)

**Comment by tfuxu** [comment]
> @tfuxu Can we add touch keyboard keys to this ? The keyboard background allready uses the theme colors, only the keys need to be adapted. ![image](https://user-images.githubusercontent.com/17254413/253003688-be38b51a-d184-4618-99ab-94248fe36768.png)

Sure, we can add it to the list

**Comment by 0xMRTT** [comment]
got it, it's already possible :)

**Comment by 0xMRTT** [comment]
![image](https://github.com/GradienceTeam/Gradience/assets/105598867/ebdb3abc-315a-4714-afa4-d02a18e5645d)

`$key_bg_color` = `darken($osd_fg_color, 70%);` and `osd_fg_color` can be set here:

![image](https://github.com/GradienceTeam/Gradience/assets/105598867/8980f66f-1433-4bd8-bb8a-dd3dbe1068c6)

I agree that it looks a wrong but the idea is here :). It will require a bit more customization for having the background

**Comment by 0xMRTT** [comment]
without any tweaks, just by using the Catpuccin Mocha preset I got :

![image](https://github.com/GradienceTeam/Gradience/assets/105598867/7a8cc21f-844c-4dcf-8dd5-e66d2c458e44)

:warning: you need to use nightly for having the Shell theming feature

**Comment by tfuxu** [comment]
Great, first one off the list :ballot_box_with_check:

**Comment by 0xMRTT** [comment]
@tfuxu I'm going to fix them soon

**Comment by sidevesh** [comment]
@0xMRTT I don't see where I can add these options, I see `osd_fg_color` already there in that list but not `key_bg_color`, and I don't see how I can add it

**Comment by 0xMRTT** [comment]
@sidevesh That's because there isn't `key_bg_color` `osd_fg_color` do the job. Have a look at the catpuccin Mocha theme!

**Comment by sidevesh** [comment]
Another issue I saw that started happening recently on my Arch system, not sure what caused it,
looks like geary's sidebar does not get the color changed anymore
![Screenshot from 2023-07-31 19-48-51](https://github.com/GradienceTeam/Gradience/assets/17254413/cb5030dc-43ac-4a61-b384-000ac746ab23)

**Comment by sidevesh** [comment]
![Screenshot from 2023-07-31 19-48-51](https://github.com/GradienceTeam/Gradience/assets/17254413/76d4f82c-137c-47fa-8e8d-085c93c8e44a)
Found another issue that started happening recently, the sidebar in Geary seems to not get its color updated anymore,
not sure if this happened due to updates to the app or adw-gtk3 theme (Geary is  still using gtk3)

**Comment by sidevesh** [comment]
I couldn't test with newest commits since the arch aur gradience-git package is broken currently and does not build anymore

**Comment by 0xMRTT** [comment]
QS Menu issue has been fixed!

**Comment by sidevesh** [comment]
@0xMRTT do you have any idea about the Geary sidebar issue I shared above ?

**Comment by 0xMRTT** [comment]
@sidevesh I don't have it...

![image](https://github.com/GradienceTeam/Gradience/assets/105598867/a1544e4a-39cd-406e-bbc5-3819e9f7f0e2)

**Comment by sidevesh** [comment]
weird, its still happening for me on arch, what theme is that which you have applied ?

**Comment by 0xMRTT** [comment]
@sidevesh i've applied Pretty Purple

**Comment by sidevesh** [comment]
Yeah, I had tried with that theme too, same issue in geary still, weird

**Comment by 0xMRTT** [comment]
@sidevesh what's your version of geary ?

**Comment by sidevesh** [comment]
44.0 (tags/44.0-0-gb72db2a5e)

**Comment by 0xMRTT** [comment]
@sidevesh The issue here is that the sidebar is plain (no Gradience, and no adw-gtk3). Can you try removing ~/.config/gtk-3.0/gtk.css, kill geary and see if it's plain adw-gtk3 even for the sidebar. If not, try updating adw-gtk3...

**Comment by 0xMRTT** [comment]
I mean that the colour of the sidebar is the one that the sidebar should have without any theming ?

**Comment by sidevesh** [comment]
I am not sure what happened put after removing ~/.config/gtk-3.0/gtk.css and then applying theme from gradience, at some point that file got deleted and is not coming back.

**Comment by sidevesh** [comment]
Looks like gradience is completed borked now :(
I can regenerate the gtk.css from Material You shell extension but then applying from Gradience deletes it again.
No idea how this happened.

**Comment by Reinachan** [comment]
Some accent colours make the quick settings look a bit off.

Notice the dark line on the active pills with dropdowns. It ends up oversaturated and looks almost like it's too wide?
![screenshot of quick settings, themed](https://github.com/GradienceTeam/Gradience/assets/16106839/366d0292-a305-49e5-b215-aeeb29f6e2a0)

This is how the default colours are. As you can see, that line doesn't stick out as much here.
![screenshot of quick settings, default](https://github.com/GradienceTeam/Gradience/assets/16106839/7d0c1698-a1b4-41f3-b1da-15a1997acff3)

I'm using the 0.8.0-beta1 from flathub. Colours are:
```
Both backgrounds: #0d0d0d
All foregrounds: #ffffff
Accent: #ff8686
```

**Comment by inthreedee** [comment]
The sidebar color issue with Geary that was mentioned by @sidevesh above (https://github.com/GradienceTeam/Gradience/issues/763#issuecomment-1660237698) appears to be an upstream adw-gtk3 v4.9 issue, as downgrading to adw-gtk3 v4.8 fixes it. I've reported it here: https://github.com/lassekongo83/adw-gtk3/issues/240

**Comment by 0xMRTT** [comment]
@inthreedee This issue is part of the new Libadwaita 1.4 widgets (sidebar and secondary sidebar). You can configure this vars with Gradience nightly

![image](https://github.com/GradienceTeam/Gradience/assets/105598867/686fd3f5-4328-4233-905e-5ba3c0c6a295)

**Comment by ParaSpl01t** [comment]
Is shell theming available in GNOME 45.2 right now?
I'm using gradience-git 0.8.0.beta1.r96.gab70ed87-1 from aur
Everything works using pretty purple theme except shell gnome shell quick settings.

**Comment by manan-gup** [comment]
Hi, I've installed the `0.8.0-beta1-36b91fe` flatpak nightly package. I tried applying the shell theme using the apply button in the shell engine section but nothing happened. Tried logging out too to no avail. Can I do anything to troubleshoot this?

**Comment by daudix** [comment]
@manan-gup do you have "User Themes" extension installed and enabled?

**Comment by manan-gup** [comment]
Yes I do. Should I disable it?

**Comment by daudix** [comment]
Nope. Could you check if there are theme with gradience in the name available? If there are one select it

**Comment by manan-gup** [comment]
![image](https://github.com/GradienceTeam/Gradience/assets/77879361/dd3ea766-b8e7-4ab5-8f53-fe25f4fbbc11)
This is what I'm getting. The `Sweet*` themes have been manually installed.

**Comment by daudix** [comment]
Hm, odd, you sure you press the right apply button? (you need to press apply that are located in the shell theming section)

**Comment by manan-gup** [comment]
![image](https://github.com/GradienceTeam/Gradience/assets/77879361/2cc9108a-f882-4afc-8bce-c9b7f47873b5)
Yes, I pressed this one.

**Comment by daudix** [comment]
Alright, can you launch it from terminal with `flatpak run com.github.GradienceTeam.Gradience` and send the output here please

**Comment by manan-gup** [comment]
```
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/gradience/frontend/widgets/shell_theming_group.py", line 113, in on_apply_button_clicked
    user_themes_available = is_shell_ext_installed(ShellTheme().THEME_EXT_NAME)
                                                   ^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/gradience/backend/theming/shell.py", line 59, in __init__
    self._detect_shell_version()
  File "/app/lib/python3.11/site-packages/gradience/backend/theming/shell.py", line 326, in _detect_shell_version
    raise UnsupportedShellVersion(
gradience.backend.exceptions.UnsupportedShellVersion: GNOME Shell version 45 is not supported. (Supported versions: 42, 43, 44)
```
Oh, my bad. I didn't know that Gnome 45 is not supported.

**Comment by daudix** [comment]
Hm, it should be, try this build: https://github.com/GradienceTeam/Gradience/actions/runs/7214048889/artifacts/1115721706

**Comment by manan-gup** [comment]
> Hm, it should be, try this build: https://github.com/GradienceTeam/Gradience/actions/runs/7214048889/artifacts/1115721706

It worked with this build.

**Comment by daudix** [comment]
You're welcome ^^

**Comment by CaragC** [comment]
Using [this](https://github.com/GradienceTeam/Gradience/actions/runs/7214048889/artifacts/1115721706) build, when clicking the apply button next to "Shell Theming Options", nothing happens. The console prints out the following when running `flatpak run com.github.GradienceTeam.Gradience.Devel` 
```
[Gradience] DEBUG: Spawning: ['flatpak-spawn', '--host', 'gnome-shell', '--version']

** (gradience:2): WARNING **: 15:59:06.037: Failed to load shared library 'libportal.so.1' referenced by the typelib: /app/lib/libportal.so.1: undefined symbol: g_once_init_leave_pointer
/app/lib/python3.11/site-packages/gradience/backend/globals.py:98: Warning: cannot retrieve class for invalid (unclassed) type 'void'
  portal = Xdp.Portal()
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/gradience/frontend/widgets/shell_theming_group.py", line 113, in on_apply_button_clicked
    user_themes_available = is_shell_ext_installed(ShellTheme().THEME_EXT_NAME)
                                                   ^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/gradience/backend/theming/shell.py", line 75, in __init__
    settings_retriever = FlatpakGSettings if is_sandboxed() else GSettingsSetting
                                             ^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/gradience/backend/globals.py", line 98, in is_sandboxed
    portal = Xdp.Portal()
             ^^^^^^^^^^^^
TypeError: could not get a reference to type class

```

Is there anyway to fix this?

**Comment by daudix** [comment]
@CaragC do you have `User Themes` extension installed? it is needed for the shell theming to work

**Comment by CaragC** [comment]
Yes it is installed and does not show any Gradience themes. The second theme I installed myself.
![image](https://github.com/GradienceTeam/Gradience/assets/70698008/9644d5fc-bfdf-42f3-8c03-3313b15c62d8)

**Comment by daudix** [comment]
Hm, that's weird, can you try the latest build? https://nightly.link/GradienceTeam/Gradience/workflows/build/main

**Comment by CaragC** [comment]
This still gives the same error as before
```
[Gradience] DEBUG: Spawning: ['flatpak-spawn', '--host', 'gnome-shell', '--version']

** (gradience:2): WARNING **: 18:35:31.542: Failed to load shared library 'libportal.so.1' referenced by the typelib: /app/lib/libportal.so.1: undefined symbol: g_once_init_leave_pointer
/app/lib/python3.11/site-packages/gradience/backend/globals.py:98: Warning: cannot retrieve class for invalid (unclassed) type 'void'
  portal = Xdp.Portal()
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/gradience/frontend/widgets/shell_theming_group.py", line 113, in on_apply_button_clicked
    user_themes_available = is_shell_ext_installed(ShellTheme().THEME_EXT_NAME)
                                                   ^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/gradience/backend/theming/shell.py", line 75, in __init__
    settings_retriever = FlatpakGSettings if is_sandboxed() else GSettingsSetting
                                             ^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/gradience/backend/globals.py", line 98, in is_sandboxed
    portal = Xdp.Portal()
             ^^^^^^^^^^^^
TypeError: could not get a reference to type class

```

**Comment by manan-gup** [comment]
> Failed to load shared library 'libportal.so.1'

Do you have the `xdg-desktop-portal` package installed?

**Comment by CaragC** [comment]
Both of the packages are installed

**Comment by sidevesh** [comment]
Another issue with Geary after fixing the earlier issue by adding the Adw 1.4 colors to the theme json,
![image](https://github.com/GradienceTeam/Gradience/assets/17254413/506268ae-70e9-4eb4-b375-f859078c583d)
this happens when window is not in foreground,
I can't figure out which backdrop or otherwise color maps to this #ffffff color.

**Comment by sidevesh** [comment]
Any idea about the above issue @daudix ?

**Comment by daudix** [comment]
I've no idea, the version from `main` has some issues with sidebar theming, you can try `beta1` which appears to not have these

**Comment by drannex42** [comment]
Gnome 46 support hasn't been added, adding this so others can find it: #871
